def get_language_config(language):
    """Returns the configuration for a given language."""
    if language == "hi":
        return {
            "locale": "hi_IN",  # Default to english
            "formats": [
                "%d/%m/%Y",
                "%d-%m-%y",
                "%Y-%m-%d",
                "%d %B, %Y",
                "%B %d, %Y",
                "%d %b, %Y",
                "%Y %B %d",
                "%Y %m %d",
                "%Y-%m-%dT%H:%M:%S"
            ],
            "month_names": { # Mappings
                "January": "जनवरी",
                "February": "फरवरी",
                "March": "मार्च",
                "April": "अप्रैल",
                "May": "मई",
                "June": "जून",
                "July": "जुलाई",
                "August": "अगस्त",
                "September": "सितंबर",
                "October": "अक्टूबर",
                "November": "नवंबर",
                "December": "दिसंबर"
            },
            "currency_names": { # Mappings, adjust as needed
                "USD": "डॉलर",
                "EUR": "यूरो",
                "GBP": "पाउंड",
                "INR": "रुपये",
                "JPY": "येन"
            },
            "scientific_units": { # Mappings, adjust as needed
                "m": "मीटर",
                "cm": "सेंटीमीटर",
                "mm": "मिलीमीटर",
                "km": "किलोमीटर",
                "g": "ग्राम",
                "kg": "किलोग्राम",
                "mg": "मिलीग्राम",
                "L": "लीटर",
                "mL": "मिलीलीटर",
                "°C": "डिग्री सेल्सियस",
                "°F": "डिग्री फारेनहाइट",
                "K": "केल्विन"
                # ... and many more
            },
            "date_contexts": [
                f"यह घटना {{input_date}} को हुई।",
                f"{{input_date}} को मेरा जन्मदिन है।",
                f"उसने {{input_date}} को एक पत्र लिखा।",
                f"मीटिंग {{input_date}} को निर्धारित है।",
                f"पार्टी {{input_date}} को है।",
                f"मैंने {{input_date}} को एक टिकट बुक किया।",
                f"फिल्म {{input_date}} को रिलीज होगी।",
                f"कॉन्सर्ट {{input_date}} को है।",
                f"सेमिनार {{input_date}} को होगा।",
                f"खेल {{input_date}} को खेला जाएगा।",
                f"घोषणा {{input_date}} को की गई थी।",
                f"कार्यक्रम {{input_date}} को शुरू होगा।",
                f"परीक्षा {{input_date}} को है।",
                f"समारोह {{input_date}} को आयोजित किया गया।",
                f"उत्सव {{input_date}} से शुरू होगा।",
                f"{{input_date}} को सब मिलेंगे।",
                f"{{input_date}} को कुछ खास होने वाला है।",
                f"{{input_date}} को हम सब साथ होंगे।",
                f"{{input_date}} को सूरज ग्रहण होगा।",
                f"{{input_date}} को चंद्र ग्रहण होगा।",
                f"{{input_date}} को छुट्टी है।",
                f"{{input_date}} को स्कूल बंद रहेगा।",
                f"{{input_date}} को बैंक बंद रहेगा।",
                f"{{input_date}} को सरकारी छुट्टी है।",
                f"{{input_date}} को चुनाव है।",
                f"{{input_date}} को परिणाम घोषित किए जाएंगे।",
                f"{{input_date}} को नया प्रोजेक्ट शुरू होगा।",
                f"{{input_date}} को नया ऑफिस खुलेगा।",
                f"{{input_date}} को दुकान खुलेगी।",
                f"{{input_date}} को प्रदर्शनी शुरू होगी।",
                f"मेरी ट्रेन {{input_date}} को है।",
                f"मेरी फ्लाइट {{input_date}} को है।",
                f"मेरा अपॉइंटमेंट {{input_date}} को है।",
                f"डॉक्टर का अपॉइंटमेंट {{input_date}} को है।",
                f"डेंटिस्ट का अपॉइंटमेंट {{input_date}} को है।",
                f"बाल कटवाने का अपॉइंटमेंट {{input_date}} को है।",
                f"{{input_date}} को मैं दिल्ली जा रहा हूँ।",
                f"{{input_date}} को मैं मुंबई जा रहा हूँ।",
                f"{{input_date}} को मैं अपने गाँव जा रहा हूँ।",
                f"{{input_date}} को मैं विदेश जा रहा हूँ।",
                f"मैं {{input_date}} को वापस आऊंगा।",
                f"मेरी छुट्टी {{input_date}} से शुरू होती है।",
                f"मेरी छुट्टी {{input_date}} को खत्म होती है।",
                f"मुझे {{input_date}} को ऑफिस जाना है।",
                f"{{input_date}} को मुझे एक जरूरी काम है।",
                f"{{input_date}} को मेरा इंटरव्यू है।",
                f"{{input_date}} को मुझे प्रेजेंटेशन देना है।",
                f"{{input_date}} को मेरा वीजा आ रहा है।",
                f"{{input_date}} को मेरा पासपोर्ट आ रहा है।",
                f"{{input_date}} को मेरी ट्रेन छूट जाएगी।",
                f"{{input_date}} तक मुझे यह काम पूरा करना है।",
                f"{{input_date}} से पहले मुझे यह काम पूरा करना है।",
                f"मैं {{input_date}} को तुमसे मिलूंगा।",
                f"क्या हम {{input_date}} को मिल सकते हैं?",
                f"{{input_date}} को मेरा दोस्त आ रहा है।",
                f"{{input_date}} को मेरा परिवार आ रहा है।",
                f"{{input_date}} को मुझे हवाई अड्डे पर जाना है।",
                f"{{input_date}} को मुझे स्टेशन पर जाना है।",
                f"{{input_date}} को मुझे बस स्टैंड पर जाना है।",
                f"{{input_date}} को मेरी बस है।",
                f"यह असाइनमेंट {{input_date}} तक जमा करना है।",
                f"बिल {{input_date}} तक देना है।",
                f"रेंट {{input_date}} तक देना है।",
                f"लोन की किस्त {{input_date}} तक देनी है।",
                f"क्रेडिट कार्ड का बिल {{input_date}} तक देना है।",
                f"यह काम {{input_date}} तक पूरा करना है।",
                f"मैंने {{input_date}} तक का समय दिया है।",
                f"{{input_date}} तक का समय काफी है।",
                f"{{input_date}} को मुझे यह याद दिलाना।",
                f"{{input_date}} को मुझे फोन करना।",
                f"{{input_date}} को मुझे मैसेज करना।",
                f"{{input_date}} को मुझे ईमेल करना।",
                f"{{input_date}} को मुझे यह फाइल भेजनी है।",
                f"{{input_date}} को मुझे यह रिपोर्ट जमा करनी है।",
                f"{{input_date}} को मुझे यह फॉर्म भरना है।",
                f"{{input_date}} को मुझे यह परीक्षा देनी है।",
                f"{{input_date}} को मुझे यह टेस्ट देना है।",
                f"{{input_date}} को मुझे यह इंटरव्यू देना है।",
                f"{{input_date}} को मुझे यह प्रेजेंटेशन देना है।",
                f"{{input_date}} को मुझे यह मीटिंग अटेंड करनी है।",
                f"{{input_date}} को मुझे यह क्लास अटेंड करनी है।",
                f"{{input_date}} को मुझे यह कोर्स पूरा करना है।",
                f"{{input_date}} को मुझे यह प्रोजेक्ट पूरा करना है।",
                f"{{input_date}} को मुझे यह काम सबमिट करना है।",
                f"{{input_date}} तक मुझे इसका जवाब देना है।",
                f"{{input_date}} तक मुझे निर्णय लेना है।",
                f"{{input_date}} को मुझे यह सामान वापस करना है।",
                f"{{input_date}} को मुझे यह किताब वापस करनी है।",
                f"{{input_date}} को मुझे यह गाड़ी सर्विसिंग के लिए देनी है।",
                f"{{input_date}} को मुझे अपना टैक्स भरना है।",
                f"भारत {{input_date}} को स्वतंत्र हुआ था।",
                f"गांधीजी का जन्म {{input_date}} को हुआ था।",
                f"मैंने {{input_date}} को अपना पहला घर खरीदा था।",
                f"हम {{input_date}} को पहली बार मिले थे।",
                f"मेरी शादी {{input_date}} को हुई थी।",
                f"मेरे बच्चे का जन्म {{input_date}} को हुआ था।",
                f"{{input_date}} को मैंने अपनी नौकरी शुरू की थी।",
                f"{{input_date}} को मैंने अपनी पढ़ाई पूरी की थी।",
                f"{{input_date}} को मैंने अपनी कंपनी शुरू की थी।",
                f"{{input_date}} को मेरी कंपनी स्थापित हुई थी।",
                f"{{input_date}} को वह दुर्घटना हुई थी।",
                f"{{input_date}} को वह युद्ध शुरू हुआ था।",
                f"{{input_date}} को वह तूफान आया था।",
                f"{{input_date}} को वह भूकंप आया था।",
                f"{{input_date}} को वह सुनामी आई थी।",
                f"{{input_date}} को वह घटना घटी थी।",
                f"{{input_date}} को मैंने यह फिल्म देखी थी।",
                f"{{input_date}} को मैंने यह किताब पढ़ी थी।",
                f"{{input_date}} को मैंने यह गाना सुना था।",
                f"{{input_date}} को मैंने यह खबर सुनी थी।",
                f"{{input_date}} को मैंने यह कहानी पढ़ी थी।",
                f"{{input_date}} को मैंने यह कविता पढ़ी थी।",
                f"{{input_date}} को मैंने यह लेख पढ़ा था।",
                f"{{input_date}} को मैंने यह निबंध लिखा था।",
                f"{{input_date}} को मैंने यह पत्र लिखा था।",
                f"{{input_date}} को मैंने यह मैसेज भेजा था।",
                f"{{input_date}} को मैंने यह ईमेल भेजा था।",
                f"{{input_date}} को मैंने यह फाइल भेजी थी।",
                f"{{input_date}} को मैंने यह रिपोर्ट जमा की थी।",
                f"{{input_date}} को मैंने यह फॉर्म भरा था।",
                f"हर साल {{input_date}} को हम यह मनाते हैं।",
                f"हर महीने की {{input_date}} को मेरी सैलरी आती है।",
                f"हर हफ्ते {{input_date}} को हम मूवी देखने जाते हैं।",
                f"हर सोमवार को {{input_date}} को ऑफिस बंद रहता है।",
                f"हर मंगलवार को {{input_date}} को क्लास होती है।",
                f"हर बुधवार को {{input_date}} को मीटिंग होती है।",
                f"हर गुरुवार को {{input_date}} को सेमिनार होता है।",
                f"हर शुक्रवार को {{input_date}} को पार्टी होती है।",
                f"हर शनिवार को {{input_date}} को खेल खेला जाता है।",
                f"हर रविवार को {{input_date}} को छुट्टी होती है।",
                f"{{input_date}} को हर साल यह पर्व मनाया जाता है।",
                f"{{input_date}} को हर महीने मेरा बिल आता है।",
                f"{{input_date}} को हर हफ्ते मैं बाजार जाता हूं।",
                f"{{input_date}} को हर दिन सूर्य उगता है।",
                f"{{input_date}} को हर रात चांद निकलता है।",
                f"{{input_date}} को हर घंटे वह चेक इन करता है।",
                f"{{input_date}} को हर मिनट वह सांस लेता है।",
                f"{{input_date}} को हर सेकंड कुछ न कुछ होता रहता है।",
                f"{{input_date}} को हर बार वह मुस्कुराता है।",
                f"{{input_date}} को हर पल कुछ बदलता है।",
                f"{{input_date}} को बार बार वह आता है।",
                f"{{input_date}} को जल्दी उठना मेरी आदत है",
                f"{{input_date}} को देर तक जागना मेरा शौक है",
                f"{{input_date}} को मैंने हमेशा सच बोला है",
                f"{{input_date}} को वह हमेशा झूठ बोलता है",
                f"{{input_date}} को पक्षी हमेशा गाना गाते है",
                f"{{input_date}} को जानवर हमेशा आराम करते है",
                f"{{input_date}} को हवा हमेशा चलती है",
                f"{{input_date}} को पानी हमेशा बहता है",
                f"{{input_date}} को हम हमेशा प्यार करते है"
            ],
            "currency_contexts":[
                f"इसकी कीमत {{input_currency}} है।",
                f"मैंने {{input_currency}} में यह खरीदा।",
                f"यह {{input_currency}} का है।",
                f"मुझे {{input_currency}} देने होंगे।",
                f"क्या आपके पास {{input_currency}} हैं?",
                f"मुझे {{input_currency}} चाहिए।",
                f"क्या मैं {{input_currency}} से भुगतान कर सकता हूँ?",
                f"{{input_currency}} में यह बहुत महंगा है।",
                f"{{input_currency}} में यह बहुत सस्ता है।",
                f"क्या यह {{input_currency}} में उपलब्ध है?",
                f"यह {{input_currency}} का निवेश है।",
                f"{{input_currency}} में यह एक अच्छा सौदा है।",
                f"यह {{input_currency}} के लायक नहीं है।",
                f"{{input_currency}} से मेरी बचत हो रही है।",
                f"मुझे {{input_currency}} उधार चाहिए।",
                f"क्या आप मुझे {{input_currency}} दे सकते हैं?",
                f"मैं आपको {{input_currency}} वापस कर दूंगा।",
                f"मैंने {{input_currency}} कमाए।",
                f"मैंने {{input_currency}} खो दिए।",
                f"यह {{input_currency}} का दान है।",
                f"यह {{input_currency}} से चैरिटी में जाएगा।",
                f"{{input_currency}} से मैं खुश हूँ।",
                f"{{input_currency}} से मैं दुखी हूँ।",
                f"{{input_currency}} में क्या मिलेगा?",
                f"{{input_currency}} में क्या कर सकता हूँ?",
                f"क्या यह {{input_currency}} में सस्ता मिलेगा?",
                f"यह {{input_currency}} का सपना है।",
                f"{{input_currency}} से मैं अपना भविष्य बनाऊंगा।",
                f"{{input_currency}} से मेरा परिवार खुश होगा।",
                f"{{input_currency}} की मुझे जरूरत है।",
                f"{{input_currency}} का हिसाब रखो।",
                f"यह {{input_currency}} का लेनदेन है।",
                f"{{input_currency}} का बजट बनाओ।",
                f"{{input_currency}} का निवेश करो।",
                f"{{input_currency}} का दान करो।",
                f"{{input_currency}} की बचत करो।",
                f"{{input_currency}} का इस्तेमाल करो।",
                f"{{input_currency}} का दुरुपयोग मत करो।",
                f"{{input_currency}} का सम्मान करो।",
                f"{{input_currency}} की कद्र करो।",
                f"यह {{input_currency}} का मामला है।",
                f"{{input_currency}} से क्या फर्क पड़ता है?",
                f"{{input_currency}} ही सब कुछ नहीं है।",
                f"{{input_currency}} से खुशी नहीं खरीदी जा सकती।",
                f"{{input_currency}} से प्यार नहीं खरीदा जा सकता।",
                f"{{input_currency}} से दोस्ती नहीं खरीदी जा सकती।",
                f"{{input_currency}} से सम्मान नहीं खरीदा जा सकता।",
                f"{{input_currency}} से ईमानदार नहीं खरीदा जा सकता।",
                f"{{input_currency}} की ताकत बहुत बड़ी है।",
                f"{{input_currency}} से दुनिया चलती है।",
                f"{{input_currency}} का खेल निराला है।",
                f"{{input_currency}} से जिंदगी आसान हो जाती है।",
                f"{{input_currency}} से जिंदगी मुश्किल हो जाती है।",
                f"{{input_currency}} का सही इस्तेमाल करना चाहिए।",
                f"{{input_currency}} का गलत इस्तेमाल नहीं करना चाहिए।",
                f"{{input_currency}} का समझदारी से इस्तेमाल करना चाहिए।",
                f"{{input_currency}} का सावधानी से इस्तेमाल करना चाहिए।",
                f"{{input_currency}} का ईमानदारी से इस्तेमाल करना चाहिए।",
                f"{{input_currency}} का न्याय से इस्तेमाल करना चाहिए।",
                f"{{input_currency}} का सोच समझकर इस्तेमाल करना चाहिए।",
                f"{{input_currency}} का सही समय पर इस्तेमाल करना चाहिए।",
                f"{{input_currency}} का ज़रूरत के समय इस्तेमाल करना चाहिए।",
                f"{{input_currency}} से दूसरों की मदद करनी चाहिए।",
                f"{{input_currency}} से गरीबों की मदद करनी चाहिए।",
                f"{{input_currency}} से ज़रूरतमंदों की मदद करनी चाहिए।",
                f"{{input_currency}} से बीमारों की मदद करनी चाहिए।",
                f"{{input_currency}} से बेघरों की मदद करनी चाहिए।",
                f"{{input_currency}} का दान करना पुण्य है।",
                f"{{input_currency}} से मंदिर बनाना पुण्य है।",
                f"{{input_currency}} से मस्जिद बनाना पुण्य है।",
                f"{{input_currency}} से चर्च बनाना पुण्य है।",
                f"{{input_currency}} से गुरुद्वारा बनाना पुण्य है।",
                f"{{input_currency}} से स्कूल बनाना पुण्य है।",
                f"{{input_currency}} से अस्पताल बनाना पुण्य है।",
                f"{{input_currency}} से गरीबों को खाना खिलाना पुण्य है।",
                f"{{input_currency}} से प्यासों को पानी पिलाना पुण्य है।",
                f"{{input_currency}} से अनजानों की मदद करना पुण्य है।",
                f"{{input_currency}} से दूसरों को खुश करना पुण्य है।",
                f"{{input_currency}} से समाज की सेवा करना पुण्य है।",
                f"{{input_currency}} से देश की सेवा करना पुण्य है।",
                f"{{input_currency}} से दुनिया की सेवा करना पुण्य है।",
                f"{{input_currency}} से मानव जाति की सेवा करना पुण्य है।",
                f"{{input_currency}} का सही उपयोग करना धर्म है।",
                f"{{input_currency}} का गलत उपयोग करना पाप है।",
                f"{{input_currency}} का दुरुपयोग करना अपराध है।",
                f"{{input_currency}} का अनादर करना पाप है।",
                f"{{input_currency}} की चोरी करना अपराध है।",
                f"{{input_currency}} से जुआ खेलना पाप है।",
                f"{{input_currency}} से नशा करना पाप है।",
                f"{{input_currency}} से बुराई करना पाप है।",
                f"{{input_currency}} से झगड़ा करना पाप है।",
                f"{{input_currency}} से लड़ाई करना पाप है।",
                f"{{input_currency}} से खून खराबा करना पाप है।",
                f"{{input_currency}} से दूसरों को नुकसान पहुंचाना पाप है।",
                f"{{input_currency}} से गरीबों का हक मारना पाप है।",
                f"{{input_currency}} से ज़रूरतमंदों का हक मारना पाप है।",
                f"{{input_currency}} से अनाथों का हक मारना पाप है।",
                f"{{input_currency}} से विधवाओं का हक मारना पाप है।",
                f"{{input_currency}} से बेघरों का हक मारना पाप है।",
                f"{{input_currency}} से बीमारों का हक मारना पाप है।",
                f"{{input_currency}} से लाचारों का हक मारना पाप है।",
                f"क्या मैं {{input_currency}} में दे सकता हूं?",
                f"इसे खरीदने के लिए {{input_currency}} कितने लगेंगे?",
                f"{{input_currency}} से ज्यादा नहीं दे सकता।",
                f"मेरे पास बस {{input_currency}} है।",
                f"क्या यह {{input_currency}} में बिक रहा है?",
                f"{{input_currency}} का क्या मतलब है?",
                f"{{input_currency}} की शक्ति क्या है?",
                f"{{input_currency}} से कुछ नहीं होगा।",
                f"{{input_currency}} से सब कुछ हो जाएगा।",
                f"{{input_currency}} से मैं अमीर बन जाऊंगा।",
                f"{{input_currency}} से मैं गरीब बन जाऊंगा।",
                f"{{input_currency}} से शांति आएगी।",
                f"{{input_currency}} से अशांति आएगी।",
                f"{{input_currency}} से विकास होगा।",
                f"{{input_currency}} से विनाश होगा।",
                f"{{input_currency}} से जीवन मिलेगा।",
                f"{{input_currency}} से मृत्यु मिलेगी।",
                f"{{input_currency}} से स्वर्ग मिलेगा।",
                f"{{input_currency}} से नरक मिलेगा।",
                f"{{input_currency}} से भगवान मिलेंगे।",
                f"{{input_currency}} से शैतान मिलेंगे।",
                f"{{input_currency}} से दोस्त मिलेंगे।",
                f"{{input_currency}} से दुश्मन मिलेंगे।",
                f"{{input_currency}} से खुशी मिलेगी।",
                f"{{input_currency}} से गम मिलेगा।",
                f"{{input_currency}} से ज्ञान मिलेगा।",
                f"{{input_currency}} से अज्ञान मिलेगा।",
                f"{{input_currency}} से प्रकाश मिलेगा।",
                f"{{input_currency}} से अंधेरा मिलेगा।",
                f"{{input_currency}} से सच्चाई मिलेगी।",
                f"{{input_currency}} से झूठ मिलेगा।",
                f"{{input_currency}} से प्रेम मिलेगा।",
                f"{{input_currency}} से घृणा मिलेगी।",
                f"{{input_currency}} से अपनापन मिलेगा।",
                f"{{input_currency}} से परायापन मिलेगा।",
                f"{{input_currency}} से सब कुछ संभव है।",
                f"{{input_currency}} के बिना कुछ भी संभव नहीं है।"
            ],
            "scientific_unit_contexts":[
                f"इसका माप {{input_unit}} है।",
                f"यह {{input_unit}} लंबा है।",
                f"तापमान {{input_unit}} है।",
                f"इसका वजन {{input_unit}} है।",
                f"इसकी मात्रा {{input_unit}} है।",
                f"इसकी गति {{input_unit}} है।",
                f"इसकी दूरी {{input_unit}} है।",
                f"इसकी ऊंचाई {{input_unit}} है।",
                f"इसकी गहराई {{input_unit}} है।",
                f"इसकी चौड़ाई {{input_unit}} है।",
                f"यह {{input_unit}} गर्म है।",
                f"यह {{input_unit}} ठंडा है।",
                f"यह {{input_unit}} भारी है।",
                f"यह {{input_unit}} हल्का है।",
                f"यह {{input_unit}} बड़ा है।",
                f"यह {{input_unit}} छोटा है।",
                f"यह {{input_unit}} तेज़ है।",
                f"यह {{input_unit}} धीमा है।",
                f"यह {{input_unit}} दूर है।",
                f"यह {{input_unit}} पास है।",
                f"क्या यह {{input_unit}} है?",
                f"यह लगभग {{input_unit}} है।",
                f"क्या यह {{input_unit}} से ज्यादा है?",
                f"क्या यह {{input_unit}} से कम है?",
                f"इसे {{input_unit}} तक गर्म करें।",
                f"इसे {{input_unit}} तक ठंडा करें।",
                f"इसका आयतन {{input_unit}} होना चाहिए।",
                f"इसका द्रव्यमान {{input_unit}} होना चाहिए।",
                f"इसकी लम्बाई {{input_unit}} से ज्यादा नहीं होनी चाहिए।",
                f"इसकी चौड़ाई {{input_unit}} से कम नहीं होनी चाहिए।",
                f"पानी {{input_unit}} पर उबलता है।",
                f"बर्फ {{input_unit}} पर जम जाती है।",
                f"कमरे का सामान्य तापमान {{input_unit}} होता है।",
                f"मानव शरीर का सामान्य तापमान {{input_unit}} होता है।",
                f"सूर्य की सतह का तापमान लगभग {{input_unit}} है।",
                f"प्रकाश की गति लगभग {{input_unit}} है।",
                f"ध्वनि की गति लगभग {{input_unit}} है।",
                f"पृथ्वी की त्रिज्या लगभग {{input_unit}} है।",
                f"पृथ्वी का द्रव्यमान लगभग {{input_unit}} है।",
                f"सूर्य का द्रव्यमान लगभग {{input_unit}} है।",
                f"इस कमरे का क्षेत्रफल {{input_unit}} है।",
                f"इस खेत का क्षेत्रफल {{input_unit}} है।",
                f"यह जमीन {{input_unit}} में फैली हुई है।",
                f"इस पाइप का व्यास {{input_unit}} है।",
                f"इस तार का व्यास {{input_unit}} है।",
                f"यह {{input_unit}} गहरा कुआँ है।",
                f"यह {{input_unit}} ऊंचा पर्वत है।",
                f"यह {{input_unit}} लंबा पुल है।",
                f"यह {{input_unit}} चौड़ी सड़क है।",
                f"यह {{input_unit}} ऊँचाई पर स्थित शहर है।",
                f"इसकी मात्रा लगभग {{input_unit}} मापी गई है।",
                f"प्रयोग में {{input_unit}} का उपयोग किया गया।",
                f"परीक्षण के परिणाम {{input_unit}} दर्शाते हैं।",
                f"वैज्ञानिकों ने {{input_unit}} का निर्धारण किया।",
                f"यह {{input_unit}} का सटीक माप है।",
                f"{{input_unit}} में त्रुटि की संभावना है।",
                f"{{input_unit}} की गणना की गई।",
                f"{{input_unit}} का अनुमान लगाया गया।",
                f"{{input_unit}} के लिए एक सूत्र है।",
                f"{{input_unit}} की परिभाषा दी गई है।",
                f"{{input_unit}} एक महत्वपूर्ण इकाई है।",
                f"{{input_unit}} का ज्ञान आवश्यक है।",
                f"{{input_unit}} का उपयोग इंजीनियरिंग में होता है।",
                f"{{input_unit}} का उपयोग विज्ञान में होता है।",
                f"{{input_unit}} का उपयोग गणित में होता है।",
                f"{{input_unit}} का उपयोग भौतिकी में होता है।",
                f"{{input_unit}} का उपयोग रसायन विज्ञान में होता है।",
                f"{{input_unit}} का उपयोग जीव विज्ञान में होता है।",
                f"इसकी ऊर्जा {{input_unit}} है।",
                f"इसकी शक्ति {{input_unit}} है।",
                f"इसकी आवृत्ति {{input_unit}} है।",
                f"इसका वेग {{input_unit}} है।",
                f"इसका त्वरण {{input_unit}} है।",
                f"इस पर लगने वाला बल {{input_unit}} है।",
                f"इसकी प्रतिरोधकता {{input_unit}} है।",
                f"इसकी चालकता {{input_unit}} है।",
                f"इसकी धारिता {{input_unit}} है।",
                f"इसका प्रेरकत्व {{input_unit}} है।",
                f"इसकी चमक {{input_unit}} है।",
                f"इसका दबाव {{input_unit}} है।",
                f"इसकी सांद्रता {{input_unit}} है।",
                f"इसकी श्यानता {{input_unit}} है।",
                f"यह घोल {{input_unit}} सांद्र है।",
                f"इसकी शुद्धता {{input_unit}} है।",
                f"इसकी अशुद्धता {{input_unit}} है।",
                f"इसकी स्थिरता {{input_unit}} है।",
                f"इसकी अस्थिरता {{input_unit}} है।",
                f"इसकी प्रतिक्रिया दर {{input_unit}} है।",
                f"इसकी विघटन दर {{input_unit}} है।",
                f"यह {{input_unit}} घनत्व वाला पदार्थ है।",
                f"यह {{input_unit}} विशिष्ट ऊष्मा वाला पदार्थ है।",
                f"इसकी जलने की गति {{input_unit}} है।",
                f"यह {{input_unit}} प्रति सेकंड की दर से बढ़ रहा है।",
                f"यह {{input_unit}} प्रति मिनट की दर से घट रहा है।",
                f"यह {{input_unit}} का अंतर है।",
                f"यह {{input_unit}} का योग है।",
                f"यह {{input_unit}} का गुणनफल है।",
                f"यह {{input_unit}} का भागफल है।",
                f"{{input_unit}} की मदद से गणना करें।",
                f"{{input_unit}} से अनुमान लगाएं।",
                f"यह लगभग {{input_unit}} जितना बड़ा है",
                f"इसकी कीमत {{input_unit}} से तय होती है",
                f"यह {{input_unit}} के बिना पूरा नहीं हो सकता",
                f"{{input_unit}} से परिणाम प्रभावित होगा",
                f"क्या आप {{input_unit}} बता सकते है?",
                f"{{input_unit}} को ध्यान से देखना होगा",
                f"{{input_unit}} के बारे में जानकारी जरूरी है",
                f"{{input_unit}} एक रहस्यमय चीज़ है",
                f"आज का विज्ञान {{input_unit}} पर निर्भर है",
                f"{{input_unit}} से आधुनिक दुनिया बनी है",
                f"{{input_unit}} की खोज किसने की थी?",
                f"{{input_unit}} की खोज कब हुई थी?",
                f"{{input_unit}} का अविष्कार किसने किया था?",
                f"{{input_unit}} का अविष्कार कब हुआ था?",
                f"{{input_unit}} का क्या उपयोग है?",
                f"{{input_unit}} का क्या नुकसान है?",
                f"{{input_unit}} से क्या फायदा है?",
                f"{{input_unit}} से क्या खतरा है?",
                f"{{input_unit}} को कैसे मापते है?",
                f"{{input_unit}} को कैसे गिनते है?",
                f"{{input_unit}} को कैसे पहचानते है?",
                f"{{input_unit}} के बारे में और बताओ",
                f"{{input_unit}} का मतलब क्या है",
                f"{{input_unit}} का मतलब समझाओ",
                f"{{input_unit}} क्या है?",
                f"{{input_unit}} क्यों जरूरी है?",
                f"{{input_unit}} कब इस्तेमाल होता है?",
                f"{{input_unit}} कैसे काम करता है?",
                f"{{input_unit}} कहाँ मिलता है?",
                f"{{input_unit}} का क्या इतिहास है?",
                f"{{input_unit}} से क्या बनता है?",
                f"{{input_unit}} से क्या बिगड़ता है?",
                f"{{input_unit}} का भविष्य क्या है?",
                f"{{input_unit}} का वर्तमान क्या है?",
                f"{{input_unit}} का अतीत क्या था?",
                f"{{input_unit}} का क्या महत्त्व है?"
            ]
        }
    else:
        raise ValueError(f"Unsupported language: {language}")